# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               IEEE Student Branch
tagline:             'Student Branch Of Brescia'
description:         'A site that holds all the projects of the IEEESB'
url:                 https://ieee-brescia.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Nik Vinter
  url:               github.com/thevinter
  email:             nikita.brancatisano@gmail.com

# Custom vars
version:             1.0.0
